import React,{useEffect,useState} from 'react'
import api from '../services/api'
import toast from 'react-hot-toast'
import {ShieldCheck,Download,CheckCircle2,AlertTriangle,Activity} from 'lucide-react'

const card='rounded-2xl border border-slate-800 bg-slate-900/70 p-5 shadow-xl'
export default function Compliance(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);try{const r=await api.get('/enterprise/compliance/overview');setData(r.data)}catch(e){toast.error(e.response?.data?.detail||'Unable to load compliance posture')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const exportAudit=async()=>{try{const r=await api.get('/enterprise/compliance/audit-export',{responseType:'blob'});const url=URL.createObjectURL(new Blob([r.data],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='ai-firewall-audit-log.csv';a.click();URL.revokeObjectURL(url);toast.success('Audit log exported')}catch(e){toast.error(e.response?.data?.detail||'Export failed')}}
 if(loading)return <div className="min-h-screen bg-slate-950 p-8 text-slate-300">Loading compliance center…</div>
 const checks=data?.checks||{}
 return <div className="min-h-screen bg-slate-950 p-4 text-white md:p-8"><div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-medium text-cyan-400">Enterprise governance</p><h1 className="text-3xl font-bold">Compliance & audit center</h1><p className="mt-1 text-sm text-slate-400">Monitor your organization's AI security controls and export an audit trail.</p></div><button onClick={exportAudit} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-500 px-4 py-2.5 text-sm font-semibold text-slate-950"><Download size={16}/>Export audit log</button></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className={card}><p className="text-xs text-slate-400">Security posture</p><div className="mt-2 text-4xl font-bold">{data?.score??0}%</div><p className="mt-1 text-xs text-slate-500">Configured enterprise controls</p></div><div className={card}><p className="text-xs text-slate-400">AI requests</p><div className="mt-2 text-3xl font-bold">{data?.metrics?.total_requests??0}</div></div><div className={card}><p className="text-xs text-slate-400">Blocked</p><div className="mt-2 text-3xl font-bold">{data?.metrics?.blocked_requests??0}</div></div><div className={card}><p className="text-xs text-slate-400">Protected applications</p><div className="mt-2 text-3xl font-bold">{data?.metrics?.active_applications??0}</div></div></div>
 <div className="mt-6 grid gap-5 lg:grid-cols-2"><div className={card}><div className="mb-4 flex items-center gap-2"><ShieldCheck className="text-cyan-400"/><h2 className="font-semibold">Control checklist</h2></div><div className="space-y-2">{Object.entries(checks).map(([key,value])=><div key={key} className="flex items-center justify-between rounded-xl border border-slate-800 p-3"><span className="text-sm text-slate-300">{key.replaceAll('_',' ')}</span>{value?<CheckCircle2 size={18} className="text-emerald-400"/>:<AlertTriangle size={18} className="text-amber-400"/>}</div>)}</div></div><div className={card}><div className="mb-4 flex items-center gap-2"><Activity className="text-cyan-400"/><h2 className="font-semibold">Organization coverage</h2></div><div className="space-y-4 text-sm"><div className="flex justify-between"><span className="text-slate-400">Active employees</span><b>{data?.metrics?.active_members??0}</b></div><div className="flex justify-between"><span className="text-slate-400">Active API keys</span><b>{data?.metrics?.active_api_keys??0}</b></div><div className="flex justify-between"><span className="text-slate-400">Enabled security policies</span><b>{data?.metrics?.enabled_policies??0}</b></div><div className="flex justify-between"><span className="text-slate-400">Verified domains</span><b>{data?.metrics?.verified_domains??0}</b></div></div><p className="mt-6 text-xs text-slate-500">This posture score is an operational readiness indicator, not a legal certification or compliance attestation.</p></div></div></div></div>
}
