import React,{useEffect,useState} from 'react'
import api from '../services/api'
import toast from 'react-hot-toast'
import {ShieldCheck,Download,CheckCircle2,AlertTriangle,Activity,LockKeyhole} from 'lucide-react'

const card='af-card af-card-pad'
export default function Compliance(){
 const [data,setData]=useState(null),[policy,setPolicy]=useState({require_mfa:false,require_sso:false}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
 const load=async()=>{setLoading(true);try{const [r,s]=await Promise.all([api.get('/enterprise/compliance/overview'),api.get('/enterprise/governance/settings')]);setData(r.data);setPolicy({require_mfa:Boolean(s.data?.settings?.require_mfa),require_sso:Boolean(s.data?.settings?.require_sso)})}catch(e){toast.error(e.response?.data?.detail||'Unable to load compliance posture')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const savePolicy=async(next)=>{setSaving(true);try{const r=await api.patch('/enterprise/auth/policy',next);setPolicy({require_mfa:Boolean(r.data.settings.require_mfa),require_sso:Boolean(r.data.settings.require_sso)});toast.success('Organization authentication policy updated')}catch(e){toast.error(e.response?.data?.detail||'Only the organization owner can change authentication policy')}finally{setSaving(false)}}
 const exportAudit=async()=>{try{const r=await api.get('/enterprise/compliance/audit-export',{responseType:'blob'});const url=URL.createObjectURL(new Blob([r.data],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='ai-firewall-audit-log.csv';a.click();URL.revokeObjectURL(url);toast.success('Audit log exported')}catch(e){toast.error(e.response?.data?.detail||'Export failed')}}
 if(loading)return <div className="min-h-screen bg-slate-950 p-8 text-slate-300">Loading compliance center…</div>
 const checks=data?.checks||{}
 return <div className="af-page"><div><div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="af-eyebrow">Enterprise governance / audit intelligence</div><h1 className="af-title">Compliance Command</h1><p className="mt-1 text-sm text-slate-400">Monitor AI security controls, authentication posture and export an audit trail.</p></div><button onClick={exportAudit} className="inline-flex items-center justify-center gap-2 af-btn af-btn-primary"><Download size={16}/>Export audit log</button></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className={card}><p className="af-label">Security posture</p><div className="mt-2 af-value">{data?.score??0}%</div><p className="mt-1 text-xs text-slate-500">Configured enterprise controls</p></div><div className={card}><p className="af-label">AI requests</p><div className="mt-2 af-value">{data?.metrics?.total_requests??0}</div></div><div className={card}><p className="af-label">Blocked</p><div className="mt-2 af-value">{data?.metrics?.blocked_requests??0}</div></div><div className={card}><p className="af-label">Protected applications</p><div className="mt-2 af-value">{data?.metrics?.active_applications??0}</div></div></div>
 <div className="mt-6 grid gap-5 lg:grid-cols-2"><div className={card}><div className="mb-4 flex items-center gap-2"><ShieldCheck className="text-cyan-400"/><h2 className="font-semibold">Control checklist</h2></div><div className="space-y-2">{Object.entries(checks).map(([key,value])=><div key={key} className="flex items-center justify-between rounded-xl border border-slate-800/80 bg-slate-950/20 p-3"><span className="text-sm text-slate-300">{key.replaceAll('_',' ')}</span>{value?<CheckCircle2 size={18} className="text-emerald-400"/>:<AlertTriangle size={18} className="text-amber-400"/>}</div>)}</div></div>
 <div className={card}><div className="mb-4 flex items-center gap-2"><LockKeyhole className="text-cyan-400"/><h2 className="font-semibold">Organization authentication</h2></div><p className="mb-4 text-sm text-slate-400">These controls are enforced by the application backend. SSO uses the IdP configured for the organization's email domain; MFA uses Supabase Auth TOTP.</p><div className="space-y-3"><label className="flex items-center justify-between rounded-xl border border-slate-800 p-4"><span><b>Require Enterprise SSO</b><span className="block text-xs text-slate-500 mt-1">Password-only sign-in is rejected for organization members.</span></span><input type="checkbox" checked={policy.require_sso} disabled={saving} onChange={e=>savePolicy({require_sso:e.target.checked})} className="h-5 w-5 accent-cyan-400"/></label><label className="flex items-center justify-between rounded-xl border border-slate-800 p-4"><span><b>Require MFA</b><span className="block text-xs text-slate-500 mt-1">Members must reach AAL2 before protected API access.</span></span><input type="checkbox" checked={policy.require_mfa} disabled={saving} onChange={e=>savePolicy({require_mfa:e.target.checked})} className="h-5 w-5 accent-cyan-400"/></label></div><p className="mt-4 text-xs text-slate-500">Only the organization owner can change these settings.</p></div></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><div className={card}><div className="mb-4 flex items-center gap-2"><Activity className="text-cyan-400"/><h2 className="font-semibold">Organization coverage</h2></div><div className="space-y-4 text-sm"><div className="flex justify-between"><span className="text-slate-400">Active employees</span><b>{data?.metrics?.active_members??0}</b></div><div className="flex justify-between"><span className="text-slate-400">Active API keys</span><b>{data?.metrics?.active_api_keys??0}</b></div><div className="flex justify-between"><span className="text-slate-400">Enabled security policies</span><b>{data?.metrics?.enabled_policies??0}</b></div><div className="flex justify-between"><span className="text-slate-400">Verified domains</span><b>{data?.metrics?.verified_domains??0}</b></div></div><p className="mt-6 text-xs text-slate-500">This posture score is an operational readiness indicator, not a legal certification or compliance attestation.</p></div></div></div></div>
}
