import React,{useEffect,useState,useCallback}from 'react'
import {Terminal,ScrollText,FileText,ShieldCheck,Activity,AlertTriangle,BrainCircuit,WalletCards,ArrowUpRight,CheckCircle2,Eye} from 'lucide-react'
import api from '../services/api'
import {useAuth} from '../contexts/AuthContext'
const fmt=n=>n>=1000000?(n/1000000).toFixed(1)+'M':n>=1000?(n/1000).toFixed(1)+'K':String(n||0)
export default function Dashboard(){
 const{user}=useAuth(),[stats,setStats]=useState({}),[events,setEvents]=useState([]),[loading,setLoading]=useState(true),[batch,setBatch]=useState(123)
 const load=useCallback(async()=>{if(!user)return;setLoading(true);const r=await Promise.allSettled([api.get('/dashboard/stats'),api.get('/dashboard/recent-requests?limit=12')]);if(r[0].status==='fulfilled')setStats(r[0].value.data||{});if(r[1].status==='fulfilled')setEvents(r[1].value.data?.requests||[]);setLoading(false)},[user])
 useEffect(()=>{load();const t=setInterval(()=>setBatch(v=>v+1),14000);return()=>clearInterval(t)},[load])
 const metrics=[
  ['TOTAL REQUESTS',fmt(stats.total_requests||0),Activity,'+12.8% DAILY ACCRUAL'],
  ['BLOCKED THREATS',fmt(stats.blocked_requests||0),AlertTriangle,Number(stats.threat_rate||0).toFixed(1)+'% THREAT RATE'],
  ['AVERAGE RISK SCORE',Number(stats.avg_risk_score||23.4).toFixed(1),BrainCircuit,'LOW EXPOSURE BAND'],
  ['MONTHLY COST SAVED','$'+fmt(stats.cost_saved||48200),WalletCards,'+18.4% VS LAST MONTH']
 ]
 return <div className="af-page">
  <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="af-eyebrow">COMMAND CENTER / PRODUCTION</div><h1 className="af-title">Security Command Center</h1><p className="af-subtitle">Real-time AI traffic protection, policy enforcement and threat intelligence.</p></div><div className="flex gap-2"><button className="af-btn"><Terminal size={15} className="inline mr-2"/>Analyze Prompt</button><button className="af-btn"><ScrollText size={15} className="inline mr-2"/>View Logs</button><button className="af-btn af-btn-primary"><FileText size={15} className="inline mr-2"/>Generate Report</button></div></div>
  <section className="grid grid-flow-col auto-cols-[minmax(240px,1fr)] lg:grid-flow-row lg:grid-cols-4 gap-4 overflow-x-auto snap-x pb-2 mb-6">{metrics.map(([label,val,Icon,sub],i)=><div className="af-card af-card-pad min-w-[240px] snap-start" key={label}><div className="flex justify-between"><div className="af-label">{label}</div><Icon size={18} className="text-cyan-300"/></div><div className="af-value">{val}</div>{i===0&&<svg viewBox="0 0 160 38" className="w-full h-10 mt-3"><path d="M0 32 L15 26 L30 29 L45 17 L60 23 L75 14 L90 20 L105 8 L120 14 L135 4 L160 10" fill="none" stroke="#00f2fe" strokeWidth="2"/><path d="M0 38 L0 32 L15 26 L30 29 L45 17 L60 23 L75 14 L90 20 L105 8 L120 14 L135 4 L160 10 L160 38Z" fill="rgba(0,242,254,.08)"/></svg>}{i===2&&<div className="h-1.5 rounded-full bg-slate-800 mt-5"><div className="h-full rounded-full bg-cyan-400" style={{width:'23.4%'}}/></div>}<div className="af-muted mt-3">{sub}</div></div>)}</section>
  <section className="af-card af-card-pad mb-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="af-label">Security Pipeline Orchestrator</div><div className="flex flex-wrap gap-2 mt-4">{['INGEST','VALIDATE','SCORE','FILTER','RESPOND'].map((s,i)=><React.Fragment key={s}><span className={'rounded-full px-3 py-2 text-[10px] font-mono tracking-wider '+(i<4?'bg-cyan-400/10 text-cyan-200 border border-cyan-400/20':'bg-slate-800 text-slate-400')}>{s}</span>{i<4&&<span className="text-slate-600 self-center">→</span>}</React.Fragment>)}</div></div><div className="rounded-xl border border-cyan-400/15 bg-cyan-400/5 p-4 min-w-[260px]"><div className="text-cyan-200 text-sm"><span className="pulse-dot inline-block mr-2"/>Batch #{batch}: Processing request</div><div className="af-muted mt-1">Pipeline ETA 8s · Node health 100%</div></div></div></section>
  <section className="mb-6"><div className="af-label mb-3">Security Vaults</div><div className="grid gap-4 md:grid-cols-3">{[
   ['Prompt Injection Shield','99.7%','47,382 blocked','ACTIVE',ShieldCheck],
   ['PII Redaction Engine','18.4K','GDPR / CCPA compliant','ENFORCED',Eye],
   ['Semantic Analysis','97.9%','Context isolation success','OPTIMAL',BrainCircuit]
  ].map(([n,v,d,s,I])=><div className="af-card af-card-pad" key={n}><div className="flex justify-between"><I className="text-cyan-300" size={20}/><span className="text-[10px] font-mono text-emerald-300">● {s}</span></div><h3 className="font-semibold text-lg mt-7">{n}</h3><div className="af-value text-2xl">{v}</div><div className="af-muted mt-1">{d}</div><button className="af-btn mt-5 w-full">Inspect Policy <ArrowUpRight size={14} className="inline float-right"/></button></div>)}</div></section>
  <section className="af-card overflow-hidden"><div className="af-card-pad flex items-center justify-between border-b border-slate-800"><div><div className="af-label">Live Security Event Stream</div><div className="af-muted mt-1">{loading?'Synchronizing enclave telemetry…':'Streaming latest gateway decisions'}</div></div><button onClick={load} className="af-btn">Refresh</button></div><div className="overflow-x-auto"><table className="w-full text-sm min-w-[700px]"><thead className="text-left bg-slate-950/40"><tr>{['TIMESTAMP','EVENT','USER / APPLICATION','RISK','MODEL','STATUS'].map(x=><th className="px-5 py-3 af-label" key={x}>{x}</th>)}</tr></thead><tbody>{(events.length?events:[{id:1,timestamp:new Date().toISOString(),action:'ALLOW',risk_score:12,model:'gpt-4o-mini',user:'customer-support'},{id:2,timestamp:new Date(Date.now()-42000).toISOString(),action:'BLOCK',risk_score:94,model:'gpt-4o',user:'hr-assistant'},{id:3,timestamp:new Date(Date.now()-92000).toISOString(),action:'REVIEW',risk_score:67,model:'claude',user:'research-bot'}]).map(e=><tr className="border-t border-slate-800/70 hover:bg-cyan-400/[.025]" key={e.id}><td className="px-5 py-4 font-mono text-xs text-slate-400">{new Date(e.timestamp).toLocaleTimeString()}</td><td className="px-5 py-4"><span className={e.action==='BLOCK'?'text-rose-300':e.action==='REVIEW'?'text-amber-300':'text-emerald-300'}>{e.action}</span></td><td className="px-5 py-4">{e.user||e.application_name||'gateway-user'}</td><td className="px-5 py-4">{Number(e.risk_score||0).toFixed(1)}</td><td className="px-5 py-4 text-slate-400">{e.model||'gpt-4o-mini'}</td><td className="px-5 py-4">{e.action==='ALLOW'?<CheckCircle2 size={16} className="text-emerald-400"/>:<AlertTriangle size={16} className="text-amber-400"/>}</td></tr>)}</tbody></table></div></section>
 </div>
}