import React, { useEffect, useState } from 'react'
import api from '../services/api'
import toast from 'react-hot-toast'
import { Shield, Building2, KeyRound, Globe, Users, AppWindow, Eye, Copy } from 'lucide-react'

const card='rounded-2xl border border-slate-800 bg-slate-900/70 p-5 shadow-xl'
const input='w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white outline-none focus:border-cyan-500'

export default function EnterpriseSecurity(){
 const [org,setOrg]=useState(null),[connections,setConnections]=useState([]),[tokens,setTokens]=useState([]),[domains,setDomains]=useState([]),[members,setMembers]=useState([]),[apps,setApps]=useState([]),[detail,setDetail]=useState(null),[tab,setTab]=useState('identity'),[domain,setDomain]=useState(''),[token,setToken]=useState(null),[loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);try{const [o,i,t,d,m,a]=await Promise.all([api.get('/organization'),api.get('/enterprise/identity'),api.get('/enterprise/scim/tokens'),api.get('/enterprise/domains'),api.get('/organization/members'),api.get('/organization/applications')]);setOrg(o.data);setConnections(i.data?.connections||[]);setTokens(t.data?.tokens||[]);setDomains(d.data?.domains||[]);setMembers(m.data?.members||[]);setApps(a.data?.applications||[])}catch(e){toast.error(e.response?.data?.detail||'Unable to load enterprise security')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const addIdentity=async(provider)=>{try{await api.post('/enterprise/identity',{provider,name:provider==='azure'?'Microsoft Entra ID':'Google Workspace'});toast.success(`${provider==='azure'?'Entra ID':'Google Workspace'} connection saved`);load()}catch(e){toast.error(e.response?.data?.detail||'Could not save identity connection')}}
 const createToken=async()=>{try{const r=await api.post('/enterprise/scim/tokens',{name:'Directory provisioning',expires_days:365});setToken(r.data.token);toast.success('SCIM token created');load()}catch(e){toast.error(e.response?.data?.detail||'Could not create SCIM token')}}
 const addDomain=async(e)=>{e.preventDefault();try{const r=await api.post('/enterprise/domains',{domain});toast.success('Domain added');setDomain('');alert(`DNS: ${r.data.instructions.record_type} ${r.data.instructions.target}`);load()}catch(e){toast.error(e.response?.data?.detail||'Could not add domain')}}
 const verify=async(id)=>{try{const r=await api.post(`/enterprise/domains/${id}/verify`);toast.success(r.data.verified?'Domain verified':'DNS record not detected yet');load()}catch(e){toast.error(e.response?.data?.detail||'Verification failed')}}
 const showEmployee=async(id)=>{try{const r=await api.get(`/enterprise/activity/employees/${id}`);setDetail({type:'employee',...r.data})}catch(e){toast.error('Unable to load employee activity')}}
 const showApp=async(id)=>{try{const r=await api.get(`/enterprise/activity/applications/${id}`);setDetail({type:'application',...r.data})}catch(e){toast.error('Unable to load application activity')}}
 if(loading)return <div className="min-h-screen bg-slate-950 p-8 text-slate-300">Loading enterprise security…</div>
 return <div className="min-h-screen bg-slate-950 p-4 text-white md:p-8"><div className="mx-auto max-w-7xl"><div className="mb-8"><p className="text-sm font-medium text-cyan-400">Enterprise security</p><h1 className="text-3xl font-bold">{org?.name||'Organization'} security center</h1><p className="mt-1 text-sm text-slate-400">Identity, provisioning, domains and detailed AI activity.</p></div>
 <div className="mb-6 flex gap-2 overflow-x-auto border-b border-slate-800">{[['identity','Identity',Shield],['scim','SCIM',KeyRound],['domains','Domains',Globe],['activity','Activity',Eye]].map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-2 border-b-2 px-4 py-3 text-sm ${tab===id?'border-cyan-400 text-cyan-300':'border-transparent text-slate-400'}`}><Icon size={16}/>{label}</button>)}</div>
 {tab==='identity'&&<div className="grid gap-5 md:grid-cols-2"><div className={card}><div className="mb-4 flex items-center gap-2"><Building2 className="text-cyan-400"/><h2 className="font-semibold">SSO providers</h2></div><p className="mb-5 text-sm text-slate-400">Use your organization's existing identity provider. OAuth configuration is completed in the Supabase Auth provider settings.</p><div className="grid gap-3 sm:grid-cols-2"><button onClick={()=>addIdentity('azure')} className="rounded-xl border border-slate-700 p-4 text-left hover:bg-slate-800"><b>Microsoft Entra ID</b><span className="mt-1 block text-xs text-slate-400">Azure AD / Microsoft 365</span></button><button onClick={()=>addIdentity('google')} className="rounded-xl border border-slate-700 p-4 text-left hover:bg-slate-800"><b>Google Workspace</b><span className="mt-1 block text-xs text-slate-400">Google organization login</span></button></div><div className="mt-5 space-y-2">{connections.map(c=><div key={c.id} className="flex items-center justify-between rounded-xl border border-slate-800 p-3"><span>{c.name}</span><span className="text-xs text-emerald-300">{c.is_active?'Enabled':'Disabled'}</span></div>)}</div></div><div className={card}><h2 className="mb-3 font-semibold">Enterprise identity model</h2><div className="space-y-3 text-sm text-slate-300"><div>✓ Organization-scoped roles</div><div>✓ Existing employee lifecycle via SCIM</div><div>✓ SSO provider records and domain association</div><div>✓ Access can be suspended centrally</div><div>✓ AI requests remain attributable to employee/application</div></div></div></div>}
 {tab==='scim'&&<div className="grid gap-5 md:grid-cols-2"><div className={card}><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">SCIM provisioning</h2><button onClick={createToken} className="rounded-xl bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950">Create token</button></div><p className="text-sm text-slate-400">Connect Entra ID, Okta or another SCIM-capable directory to automatically provision and suspend employees.</p>{token&&<div className="mt-4 rounded-xl border border-amber-500/40 bg-amber-500/10 p-4"><div className="text-sm font-semibold text-amber-200">Copy this token now</div><code className="mt-2 block break-all text-xs text-cyan-300">{token}</code><button onClick={()=>navigator.clipboard?.writeText(token)} className="mt-2 inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-1.5 text-xs"><Copy size={14}/>Copy</button></div>}<div className="mt-5 space-y-2">{tokens.map(t=><div key={t.id} className="rounded-xl border border-slate-800 p-3"><div className="font-medium">{t.name}</div><div className="text-xs text-slate-400">Expires {new Date(t.expires_at).toLocaleDateString()} · Last used {t.last_used_at?new Date(t.last_used_at).toLocaleString():'Never'}</div></div>)}</div></div><div className={card}><h2 className="mb-3 font-semibold">SCIM endpoint</h2><code className="block rounded-xl bg-slate-950 p-4 text-xs text-cyan-300">{`${window.location.origin.replace('ai-firewall-enhanced.vercel.app','ai-firewall-enhanced.onrender.com')}/v1/enterprise/scim/${org?.slug}/Users`}</code><p className="mt-3 text-xs text-slate-400">Use the generated bearer token with your directory connector. User create and active/inactive lifecycle operations are supported.</p></div></div>}
 {tab==='domains'&&<div className="grid gap-5 md:grid-cols-2"><div className={card}><h2 className="mb-4 font-semibold">Custom domain</h2><form onSubmit={addDomain} className="flex gap-2"><input className={input} required placeholder="ai.company.com" value={domain} onChange={e=>setDomain(e.target.value)}/><button className="rounded-xl bg-cyan-500 px-4 font-semibold text-slate-950">Add</button></form><div className="mt-5 space-y-3">{domains.map(d=><div key={d.id} className="rounded-xl border border-slate-800 p-4"><div className="flex items-center justify-between"><b>{d.domain}</b><span className="text-xs text-slate-400">{d.status}</span></div><div className="mt-2 text-xs text-slate-400">CNAME → {d.verification_target}</div><button onClick={()=>verify(d.id)} className="mt-3 rounded-lg border border-slate-700 px-3 py-1.5 text-xs">Verify DNS</button></div>)}</div></div><div className={card}><h2 className="mb-3 font-semibold">TLS</h2><p className="text-sm text-slate-400">After the customer domain is attached to the Vercel project and DNS points to the required target, Vercel provisions and renews HTTPS/TLS automatically.</p><div className="mt-4 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4 text-sm text-emerald-200">No certificate files or private keys need to be uploaded to AI Firewall.</div></div></div>}
 {tab==='activity'&&<div className="grid gap-5 lg:grid-cols-2"><div className={card}><div className="mb-4 flex items-center gap-2"><Users className="text-cyan-400"/><h2 className="font-semibold">Employee activity</h2></div>{members.map(m=><button key={m.id} onClick={()=>showEmployee(m.id)} className="mb-2 flex w-full items-center justify-between rounded-xl border border-slate-800 p-4 text-left hover:bg-slate-800"><span><b>{m.full_name||m.email}</b><span className="block text-xs text-slate-400">{m.email} · {m.role}</span></span><Eye size={16}/></button>)}</div><div className={card}><div className="mb-4 flex items-center gap-2"><AppWindow className="text-cyan-400"/><h2 className="font-semibold">Application activity</h2></div>{apps.map(a=><button key={a.id} onClick={()=>showApp(a.id)} className="mb-2 flex w-full items-center justify-between rounded-xl border border-slate-800 p-4 text-left hover:bg-slate-800"><span><b>{a.name}</b><span className="block text-xs text-slate-400">{a.environment} · {a.provider} · {a.model}</span></span><Eye size={16}/></button>)}</div></div>}
 {detail&&<div className={`${card} mt-5`}><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">{detail.type==='employee'?(detail.employee?.full_name||detail.employee?.email):detail.application?.name} activity</h2><p className="text-xs text-slate-400">{detail.requests?.length||0} requests · {detail.security_events?.length||0} security events</p></div><button onClick={()=>setDetail(null)} className="text-sm text-slate-400">Close</button></div><div className="max-h-96 overflow-auto">{[...(detail.requests||[])].map(r=><div key={r.id} className="border-b border-slate-800 py-3 text-sm"><div className="flex justify-between"><span className={r.action==='BLOCK'?'text-red-300':'text-emerald-300'}>{r.action}</span><span className="text-xs text-slate-500">{r.timestamp?new Date(r.timestamp).toLocaleString():''}</span></div><div className="mt-1 text-xs text-slate-400">Model: {r.model||'—'} · Risk: {r.risk_score??0} · Latency: {Math.round(r.latency_ms||0)}ms · Cost: ${Number(r.cost||0).toFixed(4)}</div>{r.reason&&<div className="mt-1 text-xs text-slate-500">{r.reason}</div>}</div>)}</div></div>}
 </div></div>
}
