import React,{useEffect,useState} from 'react'
import api from '../services/api'
import toast from 'react-hot-toast'
import {Bell,Webhook,BarChart3,KeyRound,ShieldCheck,ChevronRight,CheckCircle2,RefreshCw,Download,Search} from 'lucide-react'

const card='af-card af-card-pad'
const input='w-full rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2 text-sm text-white outline-none focus:border-cyan-400'
const steps=[['organization','Organization'],['identity','Identity / SSO'],['application','AI application'],['policy','Security policy'],['api_key','Gateway API key'],['alerts','Security alerts']]

export default function EnterpriseOperations(){
 const [tab,setTab]=useState('onboarding'),[onboard,setOnboard]=useState(null),[alerts,setAlerts]=useState([]),[webhooks,setWebhooks]=useState([]),[rules,setRules]=useState([]),[analytics,setAnalytics]=useState(null),[retention,setRetention]=useState(null),[keys,setKeys]=useState([]),[busy,setBusy]=useState(false)
 const [filters,setFilters]=useState({start:'',end:'',search:'',action:''}); const [hook,setHook]=useState({name:'SIEM webhook',url:'',events:'security.blocked,security.high_risk,security.pii'}); const [rule,setRule]=useState({name:'High-risk activity',event_type:'security.high_risk',threshold:1,window_minutes:15})
 const load=async()=>{try{const [o,a,w,r,t,k]=await Promise.all([api.get('/enterprise/onboarding'),api.get('/enterprise/alerts'),api.get('/enterprise/webhooks'),api.get('/enterprise/alert-rules'),api.get('/enterprise/retention'),api.get('/api-keys')]);setOnboard(o.data);setAlerts(a.data.alerts||[]);setWebhooks(w.data.webhooks||[]);setRules(r.data.rules||[]);setRetention(t.data.settings);setKeys(k.data.keys||[])}catch(e){toast.error(e.response?.data?.detail||'Unable to load enterprise operations')}}
 useEffect(()=>{load()},[])
 const complete=async step=>{try{await api.post(`/enterprise/onboarding/steps/${step}`);await load()}catch(e){toast.error(e.response?.data?.detail||'Could not update onboarding')}}
 const runAnalytics=async()=>{setBusy(true);try{const r=await api.get('/enterprise/analytics',{params:filters});setAnalytics(r.data)}catch(e){toast.error(e.response?.data?.detail||'Analytics failed')}finally{setBusy(false)}}
 const addWebhook=async()=>{try{const r=await api.post('/enterprise/webhooks',{...hook,events:hook.events.split(',').map(x=>x.trim()).filter(Boolean)});toast.success(`Webhook created. Secret: ${r.data.secret}`);setHook({...hook,url:''});await load()}catch(e){toast.error(e.response?.data?.detail||'Webhook creation failed')}}
 const addRule=async()=>{try{await api.post('/enterprise/alert-rules',rule);toast.success('Alert rule created');await load()}catch(e){toast.error(e.response?.data?.detail||'Rule creation failed')}}
 const saveRetention=async()=>{try{await api.patch('/enterprise/retention',retention);toast.success('Retention settings saved');await load()}catch(e){toast.error(e.response?.data?.detail||'Settings update failed')}}
 const rotate=async id=>{if(!window.confirm('Rotate this API key? The replacement secret will only be shown once.'))return;try{const r=await api.post(`/enterprise/api-keys/${id}/rotate`,{grace_minutes:15});toast.success(`New key: ${r.data.key}`);await load()}catch(e){toast.error(e.response?.data?.detail||'Rotation failed')}}
 const exportAudit=async()=>{try{const r=await api.get('/enterprise/audit/export',{params:filters,responseType:'blob'});const u=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=u;a.download='filtered-audit.csv';a.click();URL.revokeObjectURL(u)}catch(e){toast.error('Export failed')}}
 const nav=[['onboarding','Onboarding',ShieldCheck],['alerts','Alerts',Bell],['webhooks','Webhooks / SIEM',Webhook],['analytics','Analytics',BarChart3],['keys','Key rotation',KeyRound]]
 return <div className="af-page"><div><div className="mb-6"><p className="text-sm font-medium text-cyan-400">Enterprise operations</p><h1 className="text-3xl font-bold">Security operations center</h1><p className="mt-1 text-sm text-slate-400">Alerts, SIEM delivery, analytics, retention, key lifecycle and guided onboarding.</p></div>
 <div className="mb-6 flex gap-2 overflow-x-auto">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm ${tab===id?'bg-cyan-400 font-semibold text-slate-950':'af-card text-slate-300'}`}><Icon size={16}/>{label}</button>)}</div>
 {tab==='onboarding'&&<section className={card}><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">Enterprise onboarding</h2><p className="mt-1 text-sm text-slate-400">Complete the control-plane setup in the recommended order.</p></div><div className="text-right"><div className="text-3xl font-bold">{onboard?.progress??0}%</div><div className="text-xs text-slate-500">ready</div></div></div><div className="mt-6 space-y-3">{steps.map(([id,label],i)=>{const done=onboard?.steps?.[id];return <div key={id} className="flex items-center gap-4 rounded-xl border border-slate-800 p-4"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-800 text-sm">{done?<CheckCircle2 className="text-emerald-400" size={20}/>:i+1}</div><div className="flex-1"><div className="font-medium">{label}</div><div className="text-xs text-slate-500">{done?'Configured':'Complete this control before production rollout'}</div></div>{!done&&<button onClick={()=>complete(id)} className="inline-flex items-center gap-1 rounded-lg bg-cyan-500 px-3 py-2 text-xs font-semibold text-slate-950">Mark complete<ChevronRight size={14}/></button>}</div>})}</div></section>}
 {tab==='alerts'&&<section className="grid gap-5 lg:grid-cols-2"><div className={card}><h2 className="mb-4 font-semibold">Alert rules</h2><div className="space-y-3"><input className={input} value={rule.name} onChange={e=>setRule({...rule,name:e.target.value})}/><select className={input} value={rule.event_type} onChange={e=>setRule({...rule,event_type:e.target.value})}><option value="security.blocked">Blocked requests</option><option value="security.high_risk">High-risk requests</option><option value="security.pii">PII detections</option><option value="*">Any security event</option></select><div className="grid grid-cols-2 gap-3"><input className={input} type="number" min="1" value={rule.threshold} onChange={e=>setRule({...rule,threshold:Number(e.target.value)})}/><input className={input} type="number" min="1" value={rule.window_minutes} onChange={e=>setRule({...rule,window_minutes:Number(e.target.value)})}/></div><button onClick={addRule} className="w-full af-btn af-btn-primary">Create alert rule</button></div><div className="mt-5 space-y-2">{rules.map(r=><div key={r.id} className="rounded-xl border border-slate-800 p-3 text-sm"><div className="font-medium">{r.name}</div><div className="text-xs text-slate-500">{r.event_type} · threshold {r.threshold}/{r.window_minutes}m</div></div>)}</div></div><div className={card}><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Recent alerts</h2><button onClick={load} className="text-slate-400"><RefreshCw size={16}/></button></div><div className="space-y-2">{alerts.length?alerts.map(a=><div key={a.id} className="rounded-xl border border-slate-800 p-3"><div className="flex justify-between gap-2"><b>{a.title}</b><span className="text-xs text-amber-400">{a.severity}</span></div><p className="mt-1 text-xs text-slate-400">{a.message}</p><button onClick={async()=>{await api.patch(`/enterprise/alerts/${a.id}`,{status:'resolved'});await load()}} className="mt-2 text-xs text-cyan-400">Resolve</button></div>):<p className="text-sm text-slate-500">No alerts yet.</p>}</div></div></section>}
 {tab==='webhooks'&&<section className="grid gap-5 lg:grid-cols-2"><div className={card}><h2 className="mb-4 font-semibold">Webhook / SIEM integration</h2><p className="mb-4 text-xs text-slate-500">Events are signed with HMAC-SHA256. Use HTTPS endpoints only.</p><div className="space-y-3"><input className={input} placeholder="Integration name" value={hook.name} onChange={e=>setHook({...hook,name:e.target.value})}/><input className={input} placeholder="https://siem.example.com/webhook" value={hook.url} onChange={e=>setHook({...hook,url:e.target.value})}/><input className={input} placeholder="Comma-separated events" value={hook.events} onChange={e=>setHook({...hook,events:e.target.value})}/><button onClick={addWebhook} className="w-full af-btn af-btn-primary">Create integration</button></div></div><div className={card}><h2 className="mb-4 font-semibold">Connected endpoints</h2><div className="space-y-2">{webhooks.map(w=><div key={w.id} className="rounded-xl border border-slate-800 p-3"><div className="flex justify-between"><b>{w.name}</b><span className="text-xs text-emerald-400">{w.is_active?'active':'disabled'}</span></div><div className="mt-1 truncate text-xs text-slate-400">{w.url}</div><div className="mt-1 text-xs text-slate-500">{(w.events||[]).join(', ')}</div><div className="mt-2 flex gap-3"><button onClick={()=>api.post(`/enterprise/webhooks/${w.id}/test`).then(()=>toast.success('Test sent')).catch(()=>toast.error('Test failed'))} className="text-xs text-cyan-400">Send test</button><button onClick={()=>api.delete(`/enterprise/webhooks/${w.id}`).then(load)} className="text-xs text-red-400">Remove</button></div></div>)}{!webhooks.length&&<p className="text-sm text-slate-500">No integrations configured.</p>}</div></div></section>}
 {tab==='analytics'&&<section className={card}><div className="mb-4 flex flex-wrap gap-2"><input className={input+' md:w-48'} type="date" value={filters.start} onChange={e=>setFilters({...filters,start:e.target.value})}/><input className={input+' md:w-48'} type="date" value={filters.end} onChange={e=>setFilters({...filters,end:e.target.value+'T23:59:59'})}/><select className={input+' md:w-40'} value={filters.action} onChange={e=>setFilters({...filters,action:e.target.value})}><option value="">All outcomes</option><option value="ALLOW">Allowed</option><option value="BLOCK">Blocked</option></select><div className="flex min-w-48 flex-1 items-center gap-2 rounded-xl border border-slate-700 bg-slate-950 px-3"><Search size={16} className="text-slate-500"/><input className="w-full bg-transparent py-2 text-sm outline-none" placeholder="Search audit data" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></div><button onClick={runAnalytics} className="af-btn af-btn-primary">{busy?'Loading…':'Apply filters'}</button><button onClick={exportAudit} className="inline-flex items-center gap-2 af-btn"><Download size={15}/>CSV</button></div>{analytics&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Requests',analytics.summary.total_requests],['Blocked',analytics.summary.blocked_requests],['Block rate',`${analytics.summary.block_rate.toFixed(1)}%`],['Cost',`$${analytics.summary.total_cost.toFixed(4)}`],['Latency',`${analytics.summary.avg_latency_ms.toFixed(0)}ms`]].map(([k,v])=><div className="rounded-xl border border-slate-800 p-4" key={k}><div className="text-xs text-slate-500">{k}</div><div className="mt-1 text-2xl font-bold">{v}</div></div>)}</div><div className="mt-5 max-h-96 overflow-auto rounded-xl border border-slate-800"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-slate-900"><tr><th className="p-3">Time</th><th className="p-3">Action</th><th className="p-3">Risk</th><th className="p-3">Model</th><th className="p-3">Reason</th></tr></thead><tbody>{analytics.requests.map(r=><tr key={r.id} className="border-t border-slate-800"><td className="p-3">{r.timestamp}</td><td className="p-3">{r.action}</td><td className="p-3">{r.risk_score}</td><td className="p-3">{r.model}</td><td className="p-3">{r.reason||'—'}</td></tr>)}</tbody></table></div></>}</section>}
 {tab==='keys'&&<section className="grid gap-5 lg:grid-cols-2"><div className={card}><h2 className="mb-2 font-semibold">API key lifecycle</h2><p className="mb-4 text-xs text-slate-500">Rotate keys without losing control. A 15-minute grace period is used by default.</p><div className="space-y-2">{keys.map(k=><div key={k.id} className="flex items-center gap-3 rounded-xl border border-slate-800 p-3"><KeyRound size={17} className="text-cyan-400"/><div className="flex-1"><b className="text-sm">{k.name}</b><div className="text-xs text-slate-500">{k.is_active?'active':'revoked'} · expires {k.expires_at?new Date(k.expires_at).toLocaleDateString():'never'}</div></div>{k.is_active&&<button onClick={()=>rotate(k.id)} className="rounded-lg border border-slate-700 px-3 py-1.5 text-xs">Rotate</button>}</div>)}</div></div><div className={card}><h2 className="mb-2 font-semibold">Audit retention</h2><p className="mb-4 text-xs text-slate-500">Set how long organization audit logs are retained. Minimum 7 days, maximum 10 years.</p>{retention&&<div className="space-y-3"><input className={input} type="number" min="7" max="3650" value={retention.audit_retention_days} onChange={e=>setRetention({...retention,audit_retention_days:Number(e.target.value)})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={retention.alert_email_enabled} onChange={e=>setRetention({...retention,alert_email_enabled:e.target.checked})}/>Enable email security alerts</label><input className={input} placeholder="alert recipients, comma-separated" value={(retention.alert_email_recipients||[]).join(', ')} onChange={e=>setRetention({...retention,alert_email_recipients:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/><button onClick={saveRetention} className="w-full af-btn af-btn-primary">Save retention settings</button><button onClick={()=>api.post('/enterprise/retention/cleanup').then(r=>toast.success(`${r.data.deleted} logs removed`)).catch(e=>toast.error(e.response?.data?.detail||'Cleanup failed'))} className="w-full af-btn">Run retention cleanup now</button></div>}</div></section>}
 </div></div>
}
