import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { Shield, Mail, Lock } from 'lucide-react'
import toast from 'react-hot-toast'

const Login=()=>{const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[loading,setLoading]=useState(false);const{signIn,signInWithProvider}=useAuth();const navigate=useNavigate();const submit=async e=>{e.preventDefault();setLoading(true);try{await signIn(email,password);toast.success('Logged in successfully!');navigate('/')}catch(error){toast.error(error.message||'Login failed')}finally{setLoading(false)}};const sso=async provider=>{try{await signInWithProvider(provider)}catch(error){toast.error(error.message||`${provider} SSO is not configured`)}}
return <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center px-4"><div className="max-w-md w-full bg-white rounded-2xl shadow-xl p-8"><div className="text-center mb-8"><div className="flex justify-center"><div className="p-3 bg-blue-100 rounded-full"><Shield className="w-8 h-8 text-blue-600"/></div></div><h2 className="mt-4 text-2xl font-bold text-gray-800">Welcome Back</h2><p className="text-gray-500 text-sm">Sign in to access your AI Firewall dashboard</p></div><div className="grid grid-cols-2 gap-3 mb-5"><button type="button" onClick={()=>sso('azure')} className="rounded-lg border border-gray-300 py-2.5 text-sm font-medium hover:bg-gray-50">Microsoft / Entra</button><button type="button" onClick={()=>sso('google')} className="rounded-lg border border-gray-300 py-2.5 text-sm font-medium hover:bg-gray-50">Google Workspace</button></div><div className="relative mb-5"><div className="border-t border-gray-200"/><span className="absolute left-1/2 -top-3 -translate-x-1/2 bg-white px-3 text-xs text-gray-400">or email</span></div><form onSubmit={submit} className="space-y-6"><div><label className="block text-sm font-medium text-gray-700 mb-2">Email Address</label><div className="relative"><Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" placeholder="you@example.com" required/></div></div><div><label className="block text-sm font-medium text-gray-700 mb-2">Password</label><div className="relative"><Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" placeholder="••••••••" required/></div></div><button type="submit" disabled={loading} className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-2.5 rounded-lg transition disabled:opacity-50">{loading?'Signing in...':'Sign In'}</button><div className="text-center text-sm text-gray-500">Don't have an account? <a href="/register" className="text-blue-600 hover:text-blue-700 font-medium">Sign up free</a></div></form></div></div>}
export default Login
