import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ShieldCheck, Smartphone } from 'lucide-react'
import toast from 'react-hot-toast'
import { supabase } from '../lib/supabase'
import PublicShell from '../components/PublicShell'

export default function MFA({ onVerified }) {
  const navigate = useNavigate()
  const [factor, setFactor] = useState(null), [code, setCode] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [enrolled, setEnrolled] = useState(false)
  const load = async () => { const { data, error } = await supabase.auth.mfa.listFactors(); if (error) { toast.error(error.message); setLoading(false); return }; const verified = (data?.totp || []).find(item => item.status === 'verified'); setFactor(verified || null); setEnrolled(Boolean(verified)); setLoading(false) }
  useEffect(() => { load() }, [])
  const enroll = async () => { setBusy(true); try { const { data, error } = await supabase.auth.mfa.enroll({ factorType: 'totp', friendlyName: 'AI Firewall Authenticator' }); if (error) throw error; setFactor(data); setEnrolled(false); toast.success('Authenticator enrollment started. Scan the QR code, then enter the code below.') } catch (error) { toast.error(error.message) } finally { setBusy(false) } }
  const verify = async () => { if (!factor?.id || code.length < 6) return toast.error('Enter the 6-digit authenticator code'); setBusy(true); try { const { data: challenge, error: challengeError } = await supabase.auth.mfa.challenge({ factorId: factor.id }); if (challengeError) throw challengeError; const { error } = await supabase.auth.mfa.verify({ factorId: factor.id, challengeId: challenge.id, code: code.trim() }); if (error) throw error; if (onVerified) await onVerified(); toast.success('MFA verified'); navigate('/dashboard', { replace: true }) } catch (error) { toast.error(error.message) } finally { setBusy(false) } }
  return <PublicShell eyebrow="MULTI-FACTOR AUTHENTICATION" title="Verify your identity"><div className="af-card af-card-pad max-w-xl mx-auto"><div className="flex items-center gap-3 mb-5"><span className="af-brand-icon"><ShieldCheck size={20}/></span><div><h2 className="font-semibold text-white">Organization MFA required</h2><p className="af-muted">Your organization requires a second factor before access is granted.</p></div></div>{loading ? <p className="af-muted">Checking your enrolled authenticators…</p> : !factor ? <div><p className="text-sm text-slate-300 mb-4">Set up an authenticator app. The secret is handled by Supabase Auth.</p><button onClick={enroll} disabled={busy} className="af-btn af-btn-primary">{busy ? 'Preparing…' : 'Set up authenticator'}</button></div> : !enrolled ? <div><p className="text-sm text-slate-300 mb-3">Scan this QR code with your authenticator app.</p>{factor.totp?.qr_code && <img src={factor.totp.qr_code} alt="Authenticator QR code" className="mx-auto w-48 h-48 rounded-lg bg-white p-2"/>}<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" placeholder="6-digit code" className="w-full mt-5 px-4 py-3 border border-slate-700 bg-slate-950 rounded-xl text-white"/><button onClick={verify} disabled={busy} className="af-btn af-btn-primary w-full mt-3">{busy ? 'Verifying…' : 'Verify and continue'}</button></div> : <div><div className="flex items-center gap-2 text-emerald-300 mb-4"><Smartphone size={18}/> Authenticator ready</div><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" placeholder="6-digit code" className="w-full px-4 py-3 border border-slate-700 bg-slate-950 rounded-xl text-white"/><button onClick={verify} disabled={busy} className="af-btn af-btn-primary w-full mt-3">{busy ? 'Verifying…' : 'Verify and continue'}</button></div>}</div></PublicShell>
}
